# https://github.com/jacobalberty/unifi-docker
version: "3.8"
services:
   unifi:
     image: jacobalberty/unifi:v7.2.92
     container_name: "unifi"
     restart: always
     volumes:
       - ./unifi:/unifi
     ports:
      - 3478:3478/udp   # STUN
      - 10001:10001/udp # AP discovery
      - 8080:8080/tcp   # Device/ controller comm.
      - 8443:8443/tcp   # Controller GUI/API as seen in a web browser
     environment:
       - TZ=America/Chicago
